-- tOP v0.6 QA content seed: founder/company welcome + how-to community posts.
-- Safe to re-run. Uses fixed ids + upsert; visible to all members in public/community feed.

begin;

-- QA environments can lag this column depending on migration order.
alter table if exists public.community_posts
  add column if not exists is_demo_seed boolean not null default false;

insert into public.community_posts (
  id,
  author_profile_id,
  author_id,
  author_name,
  author_avatar_url,
  title,
  body,
  category,
  post_type,
  show_author_name,
  link_url,
  photo_url,
  status,
  visibility,
  like_count,
  share_count,
  reviewed_by,
  reviewed_at,
  published_at,
  is_edited,
  is_demo_seed,
  updated_at,
  created_at
)
values
(
  'd2000000-0000-4000-8000-000000000001',
  null,
  'company-top-app',
  'Marcus & Liz (Founders)',
  '',
  'Welcome to The Outreach Project community',
  'We built this platform to make trusted support easier to find for veterans, first responders, and families. Start with your profile, save organizations you want to revisit, and use community posts to share what actually helped you. If this space serves you well, tell us what we should improve next.',
  'community_update',
  'community_update',
  true,
  '',
  '/brand-logo-site-dark.png',
  'approved',
  'community',
  0,
  0,
  'qa-seed-v06',
  now(),
  now(),
  false,
  false,
  now(),
  now() - interval '30 minutes'
),
(
  'd2000000-0000-4000-8000-000000000002',
  null,
  'company-top-app',
  'Marcus (Co-Founder)',
  '',
  'How to set up your profile in under 3 minutes',
  'Quick start: (1) complete your basic account details, (2) add your mission focus and location, and (3) keep your membership current so platform features stay unlocked. A complete profile helps us personalize the experience and helps staff route support faster when you reach out.',
  'resource_help',
  'community_update',
  true,
  '',
  '/brand-logo-mark-dark.png',
  'approved',
  'community',
  0,
  0,
  'qa-seed-v06',
  now(),
  now(),
  false,
  false,
  now(),
  now() - interval '20 minutes'
),
(
  'd2000000-0000-4000-8000-000000000003',
  null,
  'company-top-app',
  'Liz (Co-Founder)',
  '',
  'How to post in community so people can act on it',
  'When you share, include what happened, what organization or resource helped, and one practical next step another member can take today. Keep it specific and respectful. Our moderators review every post so the feed stays useful, credible, and safe for the people who need it most.',
  'community_update',
  'community_update',
  true,
  '',
  '/podcasts-demo-band.jpg',
  'approved',
  'community',
  0,
  0,
  'qa-seed-v06',
  now(),
  now(),
  false,
  false,
  now(),
  now() - interval '10 minutes'
),
(
  'd2000000-0000-4000-8000-000000000004',
  null,
  'company-top-app',
  'Marcus & Liz (Founders)',
  '',
  'How to use sponsors + podcast to support the mission',
  'Sponsor cards on the main Sponsors page are our foundational partners, and podcast sponsors live on the Podcast page. Check each card for direct links and follow-ups. If your company wants to support this work, use the sponsor flow so our team can route your application and next steps cleanly.',
  'community_update',
  'community_update',
  true,
  '',
  '/sponsors/featured-bg-rope-solutions.png',
  'approved',
  'community',
  0,
  0,
  'qa-seed-v06',
  now(),
  now(),
  false,
  false,
  now(),
  now() - interval '5 minutes'
)
on conflict (id) do update set
  author_id = excluded.author_id,
  author_name = excluded.author_name,
  title = excluded.title,
  body = excluded.body,
  category = excluded.category,
  post_type = excluded.post_type,
  photo_url = excluded.photo_url,
  status = excluded.status,
  visibility = excluded.visibility,
  reviewed_by = excluded.reviewed_by,
  reviewed_at = excluded.reviewed_at,
  published_at = excluded.published_at,
  is_demo_seed = excluded.is_demo_seed,
  updated_at = now();

commit;
