-- =============================================================================
-- PRODUCTION RLS HOTFIX — pointer (do not run this file)
-- =============================================================================
-- Supabase SQL Editor does not support \i includes.
-- Paste and run the FULL contents of:
--   web/supabase/supabase_security_advisor_rls_2026_07.sql
--
-- Dashboard: https://supabase.com/dashboard/project/xbtfoundwmhrqrbcuqcw/sql/new
--
-- Closes anon leaks on top_app_saved_org_eins (user favorites), curated_orgs,
-- nonprofit_* ETL tables, staging tables, and all other public heap tables.
-- Also sets security_invoker on views and revokes client access to MVs.
--
-- CLI (no DB password): set SUPABASE_ACCESS_TOKEN then:
--   pnpm --dir web run apply:production:rls:apply
--
-- Verify:
--   select * from public._top_rls_security_audit() where status = 'FAIL';
--   pnpm --dir web run security:rls:live
-- =============================================================================
