-- =============================================================================
-- PRODUCTION SECURITY HOTFIX — pointer (do not run this file)
-- =============================================================================
-- Supabase SQL Editor does not support \i includes.
-- Run these in order (paste full file contents into SQL editor):
--
--   1) web/supabase/supabase_security_advisor_rls_2026_07.sql
--        ENABLE+FORCE RLS, restrictive client denies, security_invoker views
--   2) web/supabase/supabase_security_advisor_functions_2026_07.sql
--        Pin function search_path; revoke anon/authenticated EXECUTE on RPCs
--
-- Dashboard: https://supabase.com/dashboard/project/xbtfoundwmhrqrbcuqcw/sql/new
--
-- CLI (no DB password): set SUPABASE_ACCESS_TOKEN then:
--   pnpm --dir web run apply:production:rls:apply
--
-- Verify:
--   select * from public._top_rls_security_audit() where status = 'FAIL';
--   pnpm --dir web run security:rls:live
-- =============================================================================
