-- Shepherd's Light Foundation — Trusted Resource catalog row (EIN 33-1313139).
insert into public.trusted_resources (
  ein,
  display_name,
  website_url,
  logo_url,
  city,
  state,
  location_label,
  nonprofit_type,
  ntee_code,
  category_key,
  short_description,
  instagram_url,
  facebook_url,
  serves_veterans,
  serves_first_responders,
  listing_status,
  sort_order,
  header_image_url,
  header_image_status,
  header_image_review_status
)
values (
  '331313139',
  'Shepherd''s Light Foundation',
  'https://shepherdslightfoundation.org/',
  '/trusted/shepherds-light-foundation-org-logo.png?v=1',
  'Jasper',
  'GA',
  'Jasper, GA',
  'Faith-based PTSD recovery for veterans and first responders',
  'F',
  'healthWellness',
  'Faith-based nonprofit offering fully sponsored outdoor peer-to-peer retreats for veterans and first responders navigating PTSD and personal struggles through The Shepherd''s Journey program.',
  'https://www.instagram.com/shepherdslightfoundation/',
  'https://www.facebook.com/share/1DAKRfo8Ro/?mibextid=wwXIfr',
  true,
  true,
  'active',
  122,
  '/trusted/shepherds-light-foundation-hero.png?v=1',
  'approved',
  'approved'
)
on conflict (ein) do update set
  display_name = excluded.display_name,
  website_url = excluded.website_url,
  logo_url = excluded.logo_url,
  city = excluded.city,
  state = excluded.state,
  location_label = excluded.location_label,
  nonprofit_type = excluded.nonprofit_type,
  ntee_code = excluded.ntee_code,
  category_key = excluded.category_key,
  short_description = excluded.short_description,
  instagram_url = excluded.instagram_url,
  facebook_url = excluded.facebook_url,
  serves_veterans = excluded.serves_veterans,
  serves_first_responders = excluded.serves_first_responders,
  listing_status = excluded.listing_status,
  sort_order = excluded.sort_order,
  header_image_url = excluded.header_image_url,
  header_image_status = excluded.header_image_status,
  header_image_review_status = excluded.header_image_review_status,
  updated_at = now();
