-- Changed by Nature Outdoors — Trusted Resource catalog row (EIN 82-2820269).
insert into public.trusted_resources (
  ein,
  display_name,
  website_url,
  logo_url,
  city,
  state,
  location_label,
  nonprofit_type,
  ntee_code,
  category_key,
  short_description,
  instagram_url,
  facebook_url,
  serves_veterans,
  serves_first_responders,
  listing_status,
  sort_order,
  header_image_url,
  header_image_status,
  header_image_review_status
)
values (
  '822820269',
  'Changed by Nature Outdoors',
  'https://changedbynatureoutdoors.org/',
  '/trusted/changed-by-nature-outdoors-org-logo.png?v=1',
  'Flagstaff',
  'AZ',
  'Flagstaff, AZ',
  'Outdoor adventures for veterans, first responders, and youth',
  'C',
  'veteransMilitary',
  'Provides free outdoor adventures nationwide for veterans, law enforcement, first responders, youth, and individuals with disabilities—kayaking, fishing, hunting, and more to reconnect and rebuild in nature.',
  'https://www.instagram.com/changed_by_nature/',
  'https://www.facebook.com/share/1FB7U6LSea/?mibextid=wwXIfr',
  true,
  true,
  'active',
  121,
  '/trusted/changed-by-nature-outdoors-hero.png?v=1',
  'approved',
  'approved'
)
on conflict (ein) do update set
  display_name = excluded.display_name,
  website_url = excluded.website_url,
  logo_url = excluded.logo_url,
  city = excluded.city,
  state = excluded.state,
  location_label = excluded.location_label,
  nonprofit_type = excluded.nonprofit_type,
  ntee_code = excluded.ntee_code,
  category_key = excluded.category_key,
  short_description = excluded.short_description,
  instagram_url = excluded.instagram_url,
  facebook_url = excluded.facebook_url,
  serves_veterans = excluded.serves_veterans,
  serves_first_responders = excluded.serves_first_responders,
  listing_status = excluded.listing_status,
  sort_order = excluded.sort_order,
  header_image_url = excluded.header_image_url,
  header_image_status = excluded.header_image_status,
  header_image_review_status = excluded.header_image_review_status,
  updated_at = now();
