-- The Rivetin' Rosie's Project — Trusted Resource catalog row (EIN 33-3897165).
insert into public.trusted_resources (
  ein,
  display_name,
  website_url,
  logo_url,
  location_label,
  nonprofit_type,
  category_key,
  short_description,
  instagram_url,
  facebook_url,
  serves_veterans,
  serves_first_responders,
  listing_status,
  sort_order,
  header_image_url,
  header_image_status,
  header_image_review_status
)
values (
  '333897165',
  'The Rivetin'' Rosie's Project',
  'https://therivetinrosiesproject.org/',
  '/trusted/the-rivetin-rosies-project-org-logo.png?v=1',
  'Utah',
  'Veteran and first responder community support',
  'veteransMilitary',
  'Pin-up service organization supporting veterans, active military, first responders, and their families with resources, community events, and the spirit of the original Rosie the Riveters.',
  'https://www.instagram.com/therivetinrosiesproject/',
  'https://www.facebook.com/share/1EUwe1ECRd/?mibextid=wwXIfr',
  true,
  true,
  'active',
  120,
  '/trusted/the-rivetin-rosies-project-hero.png?v=1',
  'approved',
  'approved'
)
on conflict (ein) do update set
  display_name = excluded.display_name,
  website_url = excluded.website_url,
  logo_url = excluded.logo_url,
  location_label = excluded.location_label,
  nonprofit_type = excluded.nonprofit_type,
  category_key = excluded.category_key,
  short_description = excluded.short_description,
  instagram_url = excluded.instagram_url,
  facebook_url = excluded.facebook_url,
  serves_veterans = excluded.serves_veterans,
  serves_first_responders = excluded.serves_first_responders,
  listing_status = excluded.listing_status,
  sort_order = excluded.sort_order,
  header_image_url = excluded.header_image_url,
  header_image_status = excluded.header_image_status,
  header_image_review_status = excluded.header_image_review_status,
  updated_at = now();
